//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicareHopitalLimite_Iqramul.Patient
{


    public partial class PatientInfo
    {

        /// <summary>
        /// UserControllForPatientInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MedicareHopitalLimite_Iqramul.UserControls.UserControllForPatientInfo UserControllForPatientInfo;
    }
}
